#!/usr/bin/env python

import sys
import logging
from website.__main__ import dispatch


logger = logging.getLogger("website")
logger.addHandler(logging.StreamHandler())


if "-v" in sys.argv or "--verbose" in sys.argv:
    logger.setLevel(logging.DEBUG)
    try:
        sys.argv.remove("-v")
    except ValueError:
        pass
    try:
        sys.argv.remove("--verbose")
    except ValueError:
        pass
exit(dispatch(*sys.argv[1:]))
